version: '3.7'
services:

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - public
      - private
    ports:
      - 9443:80
    depends_on:
      - database
    environment:
      - "PMA_HOSTS=database"
      - "PMA_USER=root"
      - "PMA_PASSWORD=secret"
    deploy:
      restart_policy:
        condition: on-failure

  # database
  database:
    image: mysql:5.6
    networks:
      - private
    volumes:
      - ./database/data:/var/lib/mysql:rw
      - ./database/conf:/etc/mysql/conf.d
    environment:
      - "MYSQL_DATABASE=mydb"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_PASSWORD=secret"
    deploy:
      restart_policy:
        condition: on-failure

networks:
  public:
  private:
