version: '3'
services:

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - public
      - private
    links:
      - database
    ports:
      - 9443:80
    environment:
      - "PMA_HOSTS=database"
      - "PMA_USER=root"
      - "PMA_PASSWORD=secret"

  # database
  database:
    image: mysql:5.6
    restart: always
    networks:
      - private
    volumes:
      - ./database:/var/lib/mysql:rw
      - ./database/conf:/etc/mysql/conf.d
    environment:
      - "MYSQL_DATABASE=mydadatabase"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

networks:
  public:
  private:
